# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7dbb79b270f6891422f13bfeea752c88220b979edbae3d8d911cd9b5ecbc1d83c477f5e5ec41eca07a2092b8db40aa9e2aa8986dcc1c9279fdf9bd84c8af97fd

test:
  secret_key_base: e827055a9b94e949a8d28c6f9c69ab3cb1f45391c9ac423436aa23f3897272b30dbaf8b6d66ed4c5795d4e81bd40ef31631a59c2de508b47ae36e7266ccbb2be

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
